---
output: github_document
knit: (function(input, ...) { rmarkdown::render(input, output_file = "README.md", envir = globalenv()) })
---

### Contents

- [Offensive and Defensive PPG]
- [Offensive and Defensive YPG]
- [Offensive and Defensive EPA]

___

```{r message = F, warning = F, include = F}
library(tidyverse)
library(tidymodels)
library(tvthemes)
library(janitor)
library(zoo)
library(glue)
library(nflfastR)
library(patchwork)

theme_custom = theme_avatar() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5, size = 9, vjust = 2.5, face = "italic"),
        plot.caption = element_text(face = "italic"),
        panel.grid.major = element_line(linewidth = 0.5, colour = "#DFDAD1"),
        panel.grid.minor = element_line(linewidth = 0.5, colour = "#DFDAD1"))

theme_set(theme_custom)

# writing then reading removes nflfastR messages
write_csv(load_pbp(season = 2024), "data/season_pbp.csv")
season_pbp = read_csv("data/season_pbp.csv", show_col_types = F)

end_games = season_pbp |>
  filter(desc == "END GAME" & season_type == "REG") |>
  select(game_id, date = game_date, week, away_team, away_score = total_away_score, home_score = total_home_score, home_team) |>
  mutate(win_team = case_when(home_score > away_score ~ home_team,
                              home_score < away_score ~ away_team,
                              home_score == away_score ~ "Tie"),
         win_score = case_when(home_score > away_score ~ home_score,
                               home_score < away_score ~ away_score,
                               home_score == away_score ~ home_score),
         lose_team = case_when(home_score > away_score ~ away_team,
                               home_score < away_score ~ home_team,
                               home_score == away_score ~ "Tie"),
         lose_score = case_when(home_score > away_score ~ away_score,
                                home_score < away_score ~ home_score,
                                home_score == away_score ~ away_score),
         game_margin = win_score - lose_score,
         total_points = win_score + lose_score)

all_teams = sort(unique(c(unique(end_games$home_team), unique(end_games$away_team))))
all_szn_dates = sort(unique(end_games$date))

team_hex = teams_colors_logos |>
  select(team = team_abbr, team_color) |>
  filter(team %in% all_teams) |>
  pull(team_color)
```

### Offensive and Defensive PPG

```{r echo = F}
get_team_off_ppg = function(tm) {
  home = end_games |> filter(home_team == tm) |> pull(home_score)
  away = end_games |> filter(away_team == tm) |> pull(away_score)
  return(round(mean(c(home, away)), 2))
}

get_team_def_ppg = function(tm) {
  home = end_games |> filter(home_team == tm) |> pull(away_score)
  away = end_games |> filter(away_team == tm) |> pull(home_score)
  return(round(mean(c(home, away)), 2))
}

team_ppg = data.frame(team = all_teams) |>
  mutate(off_ppg = sapply(team, get_team_off_ppg),
         def_ppg = sapply(team, get_team_def_ppg))

team_ppg |>
  ggplot(aes(off_ppg, def_ppg)) +
  geom_point(aes(col = team), shape = "square", size = 4, show.legend = F) +
  geom_vline(xintercept = mean(team_ppg$off_ppg), linetype = "dashed", alpha = 0.5) +
  geom_hline(yintercept = mean(team_ppg$def_ppg), linetype = "dashed", alpha = 0.5) +
  scale_color_manual(values = team_hex) +
  ggrepel::geom_text_repel(aes(label = team), size = 3) +
  scale_x_continuous(breaks = seq(0, 50, by = 5)) +
  scale_y_continuous(breaks = seq(0, 50, by = 5)) +
  labs(x = "Offensive PPG",
       y = "Defensive PPG",
       title = "Team offensive and defensive PPG")
```

___

### Offensive and Defensive YPG

```{r echo = F}
off_yds = season_pbp |>
  filter(!is.na(posteam)) |>
  group_by(team = posteam) |>
  summarise(off_yds = sum(yards_gained, na.rm = T)) |>
  arrange(desc(off_yds))

def_yds = season_pbp |>
  filter(!is.na(defteam)) |>
  group_by(team = defteam) |>
  summarise(def_yds = sum(yards_gained, na.rm = T)) |>
  arrange(def_yds)

# make reference table for games played
team_games_played = end_games |>
  count(home_team) |>
  setNames(c("team", "home")) |>
  full_join(end_games |>
  count(away_team) |>
  setNames(c("team", "away")), by = "team") |>
  transmute(team, gp = home + away)

team_ypg = off_yds |>
  inner_join(def_yds, by = "team") |>
  inner_join(team_games_played, by = "team") |>
  transmute(team,
            off_ypg = round(off_yds / gp, 2),
            def_ypg = round(def_yds / gp, 2))

team_ypg |>
  ggplot(aes(off_ypg, def_ypg)) +
  geom_point(aes(col = team), shape = "square", size = 4, show.legend = F) +
  geom_vline(xintercept = mean(team_ypg$off_ypg), linetype = "dashed", alpha = 0.5) +
  geom_hline(yintercept = mean(team_ypg$def_ypg), linetype = "dashed", alpha = 0.5) +
  scale_color_manual(values = team_hex) +
  ggrepel::geom_text_repel(aes(label = team), size = 3) +
  scale_x_continuous(breaks = seq(0, 500, by = 25)) +
  scale_y_continuous(breaks = seq(0, 500, by = 25)) +
  labs(x = "Offensive YPG",
       y = "Defensive YPG",
       title = "Scatterplot of offensive and defensive YPG")
```

___

### Offensive and Defensive EPA

```{r echo = F}
off_epa = season_pbp |>
  filter(!is.na(posteam)) |>
  group_by(team = posteam) |>
  summarise(avg_off_epa = round(mean(epa, na.rm = T), 4)) |>
  arrange(desc(avg_off_epa))

def_epa = season_pbp |>
  filter(!is.na(defteam)) |>
  group_by(team = defteam) |>
  summarise(avg_def_epa = round(mean(epa, na.rm = T), 4)) |>
  arrange(desc(avg_def_epa))

team_epa = inner_join(off_epa, def_epa, by = "team")

team_epa |>
  ggplot(aes(avg_off_epa, avg_def_epa)) +
  geom_point(aes(col = team), shape = "square", size = 4, show.legend = F) +
  geom_vline(xintercept = 0, linetype = "dashed", alpha = 0.5) +
  geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
  scale_color_manual(values = team_hex) +
  ggrepel::geom_text_repel(aes(label = team), size = 3) +
  scale_x_continuous(breaks = seq(-0.5, 0.5, by = 0.05)) +
  scale_y_continuous(breaks = seq(-0.5, 0.5, by = 0.05)) +
  labs(x = "Avg. Offensive EPA",
       y = "Avg. Defensive EPA",
       title = "Scatterplot of avg. offensive and defensive EPA")
```

















___

### Offense and Defense EPA Comparisons

```{r message = F, warning = F, echo = F}
team_epa_classes = team_epa |>
  transmute(team,
            class = case_when(avg_off_epa >= 0 & avg_def_epa < 0 ~ "Good Offense, Good Defense",
                           avg_off_epa >= 0 & avg_def_epa >= 0 ~ "Good Offense, Bad Defense",
                           avg_off_epa < 0 & avg_def_epa >= 0 ~ "Bad Offense, Bad Defense",
                           avg_off_epa < 0 & avg_def_epa < 0 ~ "Bad Offense, Good Defense"))

descs = nflfastR::fast_scraper_schedules(season = 2024) |>
  filter(week > max(end_games$week)) |>
  slice_min(week, n = 1, with_ties = T) |>
  inner_join(team_epa_classes, by = c("home_team" = "team")) |>
  rename(home_class = class) |>
  inner_join(team_epa_classes, by = c("away_team" = "team")) |>
  rename(away_class = class) |>
  mutate(desc = as.character(glue::glue("{home_team} vs. {away_team}: {home_class} vs. {away_class}"))) |>
  pull(desc)

for (desc in descs) {
  print(desc)
}
```

___

### DVOA

```{r message = F, warning = F, echo = F}
link = "https://ftnfantasy.com/dvoa/nfl/team-total-dvoa"

dvoa = read_csv("data/team_total_dvoa.csv", show_col_types = F) |>
  clean_names() |>
  distinct(team, off_dvoa, def_dvoa)

dvoa |>
  ggplot(aes(off_dvoa, def_dvoa)) +
  geom_point(aes(col = team), shape = "square", size = 4, show.legend = F) +
  geom_vline(xintercept = mean(dvoa$off_dvoa), linetype = "dashed", alpha = 0.5) +
  geom_hline(yintercept = mean(dvoa$def_dvoa), linetype = "dashed", alpha = 0.5) +
  scale_color_manual(values = team_hex) +
  ggrepel::geom_text_repel(aes(label = team), size = 3) +
  scale_x_continuous(breaks = seq(-50, 50, by = 5)) +
  scale_y_continuous(breaks = seq(-50, 50, by = 5)) +
  labs(x = "Offensive DVOA",
       y = "Defensive DVOA",
       title = "Scatterplot of offensive and defensive DVOA")
```

___

```{r echo = F}
off_pass_rush = season_pbp |>
  filter(!is.na(posteam) & play_type %in% c("pass", "run")) |>
  group_by(posteam, play_type) |>
  summarise(avg_epa = mean(epa, na.rm = T),
            .groups = "drop") |>
  pivot_wider(id_cols = "posteam", names_from = "play_type", values_from = "avg_epa") |>
  setNames(c("team", "avg_off_pass_epa", "avg_off_run_epa"))

def_pass_rush = season_pbp |>
  filter(!is.na(defteam) & play_type %in% c("pass", "run")) |>
  group_by(defteam, play_type) |>
  summarise(avg_epa = mean(epa, na.rm = T),
            .groups = "drop") |>
  pivot_wider(id_cols = "defteam", names_from = "play_type", values_from = "avg_epa") |>
  setNames(c("team", "avg_def_pass_epa", "avg_def_run_epa"))

team_off_def_pass_rush_epa = inner_join(off_pass_rush, def_pass_rush, by = "team")

total_with_epa = end_games |>
  transmute(home_team, away_team, total_score = home_score + away_score) |>
  inner_join(team_off_def_pass_rush_epa, by = c("home_team" = "team")) |>
  setNames(c("home_team", "away_team", "total_score",
             "home_avg_off_pass_epa", "home_avg_off_run_epa", "home_avg_def_pass_epa", "home_avg_def_run_epa")) |>
  inner_join(team_off_def_pass_rush_epa, by = c("away_team" = "team")) |>
  setNames(c("home_team", "away_team", "total_score",
             "home_avg_off_pass_epa", "home_avg_off_run_epa", "home_avg_def_pass_epa", "home_avg_def_run_epa",
             "away_avg_off_pass_epa", "away_avg_off_run_epa", "away_avg_def_pass_epa", "away_avg_def_run_epa")) |>
  select(-c(home_team, away_team))

total_mod = lm(total_score ~ ., data = total_with_epa)
```


```{r echo = F}
off_week_epa = season_pbp |>
  filter(!is.na(posteam)) |>
  group_by(team = posteam, week) |>
  summarise(off_epa = mean(epa, na.rm = T),
            .groups = "drop")

def_week_epa = season_pbp |>
  filter(!is.na(defteam)) |>
  group_by(team = defteam, week) |>
  summarise(def_epa = mean(epa, na.rm = T),
            .groups = "drop")

team_weekly_epa = inner_join(off_week_epa, def_week_epa, by = c("team", "week"))
```

___

### NPR Standings

```{r message = F, warning = F, echo = F}
end_npr = end_games |>
  inner_join(team_ppg, by = c("home_team" = "team")) |>
  rename(home_off_ppg = off_ppg, home_def_ppg = def_ppg) |>
  inner_join(team_ppg, by = c("away_team" = "team")) |>
  rename(away_off_ppg = off_ppg, away_def_ppg = def_ppg) |>
  mutate(home_exp = (home_off_ppg + away_def_ppg) / 2,
         away_exp = (away_off_ppg + home_def_ppg) / 2,
         home_off_npr = home_score - home_exp,
         home_def_npr = away_exp - away_score,
         away_off_npr = away_score - away_exp,
         away_def_npr = home_exp - home_score)

get_team_off_npr = function(tm) {
  home = end_npr |> filter(home_team == tm) |> pull(home_off_npr)
  away = end_npr |> filter(away_team == tm) |> pull(away_off_npr)
  return(round(mean(c(home, away)), 3))
}

get_team_def_npr = function(tm) {
  home = end_npr |> filter(home_team == tm) |> pull(home_def_npr)
  away = end_npr |> filter(away_team == tm) |> pull(away_def_npr)
  return(round(mean(c(home, away)), 3))
}

team_npr = data.frame(team = all_teams) |>
  mutate(off_npr = sapply(team, get_team_off_npr),
         def_npr = sapply(team, get_team_def_npr),
         npr = off_npr + def_npr,
         npr_rank = rank(-npr),
         team_npr = as.character(glue::glue("{team} ({npr_rank})")))

team_npr |>
  mutate(pos_lab = ifelse(npr >= 0, round(npr, 2), ""),
         neg_lab = ifelse(npr < 0, round(npr, 2), "")) |>
  ggplot(aes(reorder(team_npr, npr), npr)) +
  geom_col(aes(fill = team), show.legend = F) +
  geom_text(aes(label = pos_lab), size = 3, hjust = -0.25) +
  geom_text(aes(label = neg_lab), size = 3, hjust = 1.25) +
  scale_fill_manual(values = team_hex) +
  coord_flip(ylim = c(min(team_npr$npr) * 1.05, max(team_npr$npr) * 1.05)) +
  labs(x = NULL,
       y = "Total NPR",
       title = "2024 NPR Standings") +
  scale_y_continuous(breaks = seq(-10, 10, by = 1))
```

___

### Scatterplot of NPR

```{r echo = F}
team_npr |>
  ggplot(aes(off_npr, def_npr)) +
  geom_point(aes(col = team), shape = "square", size = 4, show.legend = F) +
  ggrepel::geom_text_repel(aes(label = team), size = 3) +
  geom_vline(xintercept = 0, linetype = "dashed", alpha = 0.5) +
  geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
  scale_color_manual(values = team_hex) +
  scale_x_continuous(breaks = seq(-10, 10, by = 1)) +
  scale_y_continuous(breaks = seq(-10, 10, by = 1)) +
  labs(x = "Offensive NPR", y = "Defensive NPR",
       title = "Scatterplot of Offensive/Defensive NPR")
```

___

### Week Predictions

```{r message = F, warning = F, echo = F}
team_npr_epa = team_npr |>
  select(team, off_npr, def_npr) |>
  inner_join(team_epa, by = "team")

home_npr_epa = team_npr_epa |>
  setNames(paste0("home_", colnames(team_npr_epa)))

away_npr_epa = team_npr_epa |>
  setNames(paste0("away_", colnames(team_npr_epa)))

mod_data = end_games |>
  inner_join(home_npr_epa, by = "home_team") |>
  inner_join(away_npr_epa, by = "away_team") |>
  mutate(home_win = as.factor(ifelse(win_team == home_team, 1, 0))) |>
  select(home_off_npr:home_win)

home_win_model = glm(home_win ~ ., data = mod_data, family = "binomial")

get_matchup_data = function(home_tm, away_tm) {
  data = data.frame(home_team = home_tm, away_team = away_tm) |>
    inner_join(home_npr_epa, by = "home_team") |>
    inner_join(away_npr_epa, by = "away_team") |>
    select(-c(home_team, away_team))
  
  return(data)
}

if (weekdays(Sys.Date()) %in% c("Friday", "Saturday", "Sunday", "Monday")) {
  this_week_num = max(end_games$week)
} else {
  this_week_num = max(end_games$week) + 1
}

this_week_data = nflfastR::fast_scraper_schedules(season = 2024) |>
  filter(week == this_week_num) |>
  select(home_team, away_team) |>
  inner_join(home_npr_epa, by = "home_team") |>
  inner_join(away_npr_epa, by = "away_team")

this_week_probs = predict(home_win_model, this_week_data, type = "response")

this_week_picks = this_week_data |>
  mutate(prob = this_week_probs,
         pred_home_win = ifelse(prob >= 0.5, 1, 0),
         pred_win_team = ifelse(pred_home_win == 1, home_team, away_team),
         pred_lose_team = ifelse(pred_home_win == 1, away_team, home_team),
         conf_raw = ifelse(prob >= 0.5, prob, 1 - prob),
         conf = paste0(round(conf_raw * 100, 1), "%"),
         desc = as.character(glue::glue("{pred_win_team} def. {pred_lose_team} ({conf})"))) |>
  arrange(desc(conf_raw))

for (pick in this_week_picks$desc) {
  print(pick)
}
```


```{r}
season_pbp |>
  filter(play_type == "pass") |>
  group_by(passer, week) |>
  summarise(n = n(),
            avg_epa = mean(epa, na.rm = T),
            .groups = "drop") |>
  filter(week == max(end_games$week) & n >= 5) |>
  arrange(desc(avg_epa)) |>
  mutate(avg_epa = round(avg_epa, 3),
         passer = as.character(glue::glue("{passer} ({round(avg_epa, 2)})"))) |>
  ggplot(aes(reorder(passer, avg_epa), avg_epa)) +
  geom_col(aes(fill = avg_epa), show.legend = F) +
  coord_flip() +
  scale_fill_gradient(low = "indianred3", high = "springgreen4") +
  labs(x = NULL, y = "Avg. EPA",
       title = "Avg. EPA by QBs this past week") +
  scale_y_continuous(breaks = seq(-1, 1, by = 0.1))
```

```{r}
team_pass_run_share = season_pbp |>
  filter(play_type %in% c("pass", "run")) |>
  group_by(team = posteam) |>
  count(play_type) |>
  mutate(pct = round(n / sum(n), 3)) |>
  ungroup()

run_heavy = team_pass_run_share |>
  filter(play_type == "run") |>
  arrange(desc(pct)) |>
  pull(team)

team_pass_run_share |>
  mutate(team = factor(team, levels = rev(run_heavy)),
         play_type = ifelse(play_type == "pass", "Pass", "Run")) |>
  ggplot(aes(team, pct)) +
  geom_col(aes(fill = play_type)) +
  coord_flip() +
  labs(x = NULL, y = "Rushing Share", fill = NULL,
       title = "Run the damn ball!") +
  scale_fill_manual(values = c("lightsteelblue3", "springgreen4")) +
  theme(legend.position = "right") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.1), labels = scales::percent)
```

```{r}
team_run_shares_vec = team_pass_run_share |>
  filter(play_type == "run") |>
  arrange(team) |>
  pull(pct)

team_off_ypg_vec = team_ypg |>
  arrange(team) |>
  pull(off_ypg)

cor_coef = round(cor(team_run_shares_vec, team_off_ypg_vec), 3)

team_pass_run_share |>
  filter(play_type == "run") |>
  select(team, run_pct = pct) |>
  inner_join(team_ypg |>
  select(team, off_ypg), by = "team") |>
  ggplot(aes(run_pct, off_ypg)) +
  geom_point(aes(col = team), size = 4, shape = "square", show.legend = F) +
  geom_line(stat = "smooth", formula = y ~ x, method = "lm", linetype = "dashed", alpha = 0.5) +
  ggrepel::geom_text_repel(aes(label = team), size = 3) +
  scale_color_manual(values = team_hex) +
  labs(x = "Rushing share", y = "Offensive YPG",
       title = "Does running the damn ball work?",
       subtitle = glue("Correlation: {cor_coef}")) +
  scale_x_continuous(breaks = seq(0, 1, by = 0.05), labels = scales::percent) +
  scale_y_continuous(breaks = seq(200, 500, by = 25))
```

```{r}
season_pbp |>
  filter(play_type %in% c("pass", "run")) |>
  group_by(team = posteam, play_type) |>
  summarise(epa = mean(epa, na.rm = T),
            .groups = "drop") |>
  pivot_wider(id_cols = team, names_from = "play_type", values_from = "epa") |>
  ggplot(aes(run, pass)) +
  geom_point(aes(col = team), size = 4, shape = "square", show.legend = F) +
  scale_color_manual(values = team_hex) +
  ggrepel::geom_text_repel(aes(label = team), size = 3, max.overlaps = 32) +
  geom_vline(xintercept = 0, linetype = "dashed", alpha = 0.5) +
  geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5)

season_pbp |>
  filter(play_type %in% c("pass", "run")) |>
  group_by(team = defteam, play_type) |>
  summarise(epa = mean(epa, na.rm = T),
            .groups = "drop") |>
  pivot_wider(id_cols = team, names_from = "play_type", values_from = "epa") |>
  ggplot(aes(run, pass)) +
  geom_point(aes(col = team), size = 4, shape = "square", show.legend = F) +
  scale_color_manual(values = team_hex) +
  ggrepel::geom_text_repel(aes(label = team), size = 3, max.overlaps = 32) +
  geom_vline(xintercept = 0, linetype = "dashed", alpha = 0.5) +
  geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5)
```





```{r}
season_pbp |>
  filter(play_type %in% c("pass", "run")) |>
  group_by(team = posteam) |>
  summarise(off_epa = mean(epa, na.rm = T)) |>
  inner_join(season_pbp |>
  filter(play_type %in% c("pass", "run")) |>
  group_by(team = defteam) |>
  summarise(def_epa = mean(epa, na.rm = T)), by = "team") |>
  mutate(ovr_epa = off_epa + def_epa) |>
  arrange(desc(ovr_epa))
```



```{r}
season_pbp |>
  filter(week >= 4) |>
  filter(play_type == "pass") |>
  group_by(passer) |>
  summarise(n = n(),
            epa_per_db = mean(epa, na.rm = T)) |>
  mutate(n_pct = percent_rank(n)) |>
  filter(n_pct >= 0.5) |>
  ggplot(aes(n, epa_per_db)) +
  geom_point() +
  ggrepel::geom_text_repel(aes(label = passer), size = 3, max.overlaps = 50) +
  labs(x = "Number of dropbacks",
       y = "EPA per dropback",
       title = "EPA per dropback",
       subtitle = "Weeks 4-6 / Only QBs in 50th percentile of higher in dropbacks") +
  scale_x_continuous(breaks = seq(0, 1000, by = 10)) +
  scale_y_continuous(breaks = seq(-1, 1, by = 0.1))
```








```{r}
season_pbp |>
  filter(play_type == "pass" & week >= 4) |>
  group_by(passer) |>
  summarise(n = n(),
            success_rate = round(mean(success, na.rm = T), 3)) |>
  mutate(n_pct = percent_rank(n)) |>
  filter(n_pct >= 0.5) |>
  arrange(desc(success_rate))
```



```{r}
team_logos = teams_colors_logos |>
  filter(team_abbr %in% all_teams) |>
  select(team_abbr, team_logo_espn)

# team success rate by down (passing and running plays)
pass_epa_success = season_pbp |>
  filter(play_type == "pass") |>
  group_by(posteam, play_type) |>
  summarise(avg_epa = mean(epa),
            success_rate = mean(success),
            .groups = "drop")

opesp = pass_epa_success |>
  ggplot(aes(avg_epa, success_rate)) +
  geom_point(aes(col = posteam), shape = "square", size = 4, show.legend = F) +
  ggrepel::geom_text_repel(aes(label = posteam), size = 3, max.overlaps = 32) +
  scale_color_manual(values = team_hex) +
  geom_line(stat = "smooth", method = "lm", formula = y ~ x, linetype = "dotted", alpha = 0.25) +
  geom_vline(xintercept = 0, linetype = "dashed", alpha = 0.5) +
  geom_hline(yintercept = mean(pass_epa_success$success_rate), linetype = "dashed", alpha = 0.5) +
  labs(x = "Offensive EPA per play, passing",
       y = "Offensive success rate, passing",
       title = "Offensive EPA per play vs. success rate by team (passing)") +
  scale_x_continuous(breaks = seq(-0.5, 0.5, by = 0.05)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.05), labels = scales::percent)

rush_epa_success = season_pbp |>
  filter(play_type == "run") |>
  group_by(posteam, play_type) |>
  summarise(avg_epa = mean(epa),
            success_rate = mean(success),
            .groups = "drop")

oresp = rush_epa_success |>
  ggplot(aes(avg_epa, success_rate)) +
  geom_point(aes(col = posteam), shape = "square", size = 4, show.legend = F) +
  ggrepel::geom_text_repel(aes(label = posteam), size = 3, max.overlaps = 32) +
  scale_color_manual(values = team_hex) +
  geom_line(stat = "smooth", method = "lm", formula = y ~ x, linetype = "dotted", alpha = 0.25) +
  geom_vline(xintercept = 0, linetype = "dashed", alpha = 0.5) +
  geom_hline(yintercept = mean(rush_epa_success$success_rate), linetype = "dashed", alpha = 0.5) +
  labs(x = "Offensive EPA per play, rushing",
       y = "Offensive success rate, rushing",
       title = "Offensive EPA per play vs. success rate by team (rushing)") +
  scale_x_continuous(breaks = seq(-0.5, 0.5, by = 0.05)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.05), labels = scales::percent)

pass_epa_success = season_pbp |>
  filter(play_type == "pass") |>
  group_by(defteam, play_type) |>
  summarise(avg_epa = mean(epa),
            success_rate = mean(success),
            .groups = "drop")

dpesp = pass_epa_success |>
  ggplot(aes(avg_epa, success_rate)) +
  geom_point(aes(col = defteam), shape = "square", size = 4, show.legend = F) +
  ggrepel::geom_text_repel(aes(label = defteam), size = 3, max.overlaps = 32) +
  scale_color_manual(values = team_hex) +
  geom_line(stat = "smooth", method = "lm", formula = y ~ x, linetype = "dotted", alpha = 0.25) +
  geom_vline(xintercept = 0, linetype = "dashed", alpha = 0.5) +
  geom_hline(yintercept = mean(pass_epa_success$success_rate), linetype = "dashed", alpha = 0.5) +
  labs(x = "Defensive EPA per play, passing",
       y = "Defensive success rate, passing",
       title = "Defensive EPA per play vs. success rate by team (passing)") +
  scale_x_continuous(breaks = seq(-0.5, 0.5, by = 0.05)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.05), labels = scales::percent)

rush_epa_success = season_pbp |>
  filter(play_type == "run") |>
  group_by(defteam, play_type) |>
  summarise(avg_epa = mean(epa),
            success_rate = mean(success),
            .groups = "drop")

dresp = rush_epa_success |>
  ggplot(aes(avg_epa, success_rate)) +
  geom_point(aes(col = defteam), shape = "square", size = 4, show.legend = F) +
  ggrepel::geom_text_repel(aes(label = defteam), size = 3, max.overlaps = 32) +
  scale_color_manual(values = team_hex) +
  geom_line(stat = "smooth", method = "lm", formula = y ~ x, linetype = "dotted", alpha = 0.25) +
  geom_vline(xintercept = 0, linetype = "dashed", alpha = 0.5) +
  geom_hline(yintercept = mean(rush_epa_success$success_rate), linetype = "dashed", alpha = 0.5) +
  labs(x = "Defensive EPA per play, rushing",
       y = "Defensive success rate, rushing",
       title = "Defensive EPA per play vs. success rate by team (rushing)") +
  scale_x_continuous(breaks = seq(-0.5, 0.5, by = 0.05)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.05), labels = scales::percent)

opesp
oresp
dpesp
dresp
```


```{r}
suppressMessages(library(ggimage))

team_logos = teams_colors_logos |>
  filter(team_abbr %in% all_teams) |>
  select(team = team_abbr, team_logo_wikipedia)

team_epa_with_logos = team_epa |>
  inner_join(team_logos, by = "team")

team_epa_with_logos |>
  ggplot(aes(avg_off_epa, avg_def_epa)) +
  geom_image(aes(image = team_logo_wikipedia), size = 0.1) +
  geom_vline(xintercept = 0, linetype = "dashed", alpha = 0.5) +
  geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
  scale_color_manual(values = team_hex) +
  labs(x = "Avg. Offensive EPA",
       y = "Avg. Defensive EPA",
       title = "Offensive and Defensive EPA") +
  scale_x_continuous(breaks = seq(-1, 1, by = 0.05)) +
  scale_y_continuous(breaks = seq(-1, 1, by = 0.05))
```


```{r}
off_qtr_epa_success = season_pbp |>
  filter(play_type %in% c("pass", "run") & qtr %in% 1:4) |>
  group_by(team = posteam, qtr) |>
  summarise(avg_epa = mean(epa, na.rm = T),
            success_rate = mean(success, na.rm = T),
            .groups = "drop")

def_qtr_epa_success = season_pbp |>
  filter(play_type %in% c("pass", "run") & qtr %in% 1:4) |>
  group_by(team = defteam, qtr) |>
  summarise(avg_epa = mean(epa, na.rm = T),
            success_rate = mean(success, na.rm = T),
            .groups = "drop")

off_qtr_epa_success |>
  mutate(qtr = case_when(qtr == 1 ~ "1st Quarter",
                         qtr == 2 ~ "2nd Quarter",
                         qtr == 3 ~ "3rd Quarter",
                         qtr == 4 ~ "4th Quarter")) |>
  group_by(qtr) |>
  slice_max(avg_epa, n = 3, with_ties = F) |>
  ungroup() |>
  ggplot(aes(reorder(team, avg_epa), avg_epa)) +
  geom_col(aes(fill = team), show.legend = F) +
  coord_flip() +
  scale_fill_manual(values = team_hex) +
  facet_wrap(vars(qtr), scales = "free_y") +
  labs(x = NULL, y = "EPA per play")

off_qtr_epa_success |>
  mutate(qtr = case_when(qtr == 1 ~ "1st Quarter",
                         qtr == 2 ~ "2nd Quarter",
                         qtr == 3 ~ "3rd Quarter",
                         qtr == 4 ~ "4th Quarter")) |>
  group_by(qtr) |>
  slice_max(avg_epa, n = 3, with_ties = F) |>
  ungroup() |>
  ggplot(aes(reorder(team, success_rate), success_rate)) +
  geom_col(aes(fill = team), show.legend = F) +
  coord_flip() +
  scale_fill_manual(values = team_hex) +
  facet_wrap(vars(qtr), scales = "free_y") +
  labs(x = NULL, y = "Offensive success rate")

def_qtr_epa_success |>
  mutate(qtr = case_when(qtr == 1 ~ "1st Quarter",
                         qtr == 2 ~ "2nd Quarter",
                         qtr == 3 ~ "3rd Quarter",
                         qtr == 4 ~ "4th Quarter")) |>
  group_by(qtr) |>
  slice_min(avg_epa, n = 3, with_ties = F) |>
  ungroup() |>
  ggplot(aes(reorder(team, avg_epa), avg_epa)) +
  geom_col(aes(fill = team), show.legend = F) +
  coord_flip() +
  scale_fill_manual(values = team_hex) +
  facet_wrap(vars(qtr), scales = "free_y") +
  labs(x = NULL, y = "EPA per play")

def_qtr_epa_success |>
  mutate(qtr = case_when(qtr == 1 ~ "1st Quarter",
                         qtr == 2 ~ "2nd Quarter",
                         qtr == 3 ~ "3rd Quarter",
                         qtr == 4 ~ "4th Quarter")) |>
  group_by(qtr) |>
  slice_min(avg_epa, n = 3, with_ties = F) |>
  ungroup() |>
  ggplot(aes(reorder(team, success_rate), success_rate)) +
  geom_col(aes(fill = team), show.legend = F) +
  coord_flip() +
  scale_fill_manual(values = team_hex) +
  facet_wrap(vars(qtr), scales = "free_y") +
  labs(x = NULL, y = "EPA per play")
```



















